create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  username text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

create policy "Profiles are viewable by authenticated users"
  on public.profiles
  for select
  to authenticated
  using (true);

create policy "Users can insert their profile"
  on public.profiles
  for insert
  to authenticated
  with check (id = auth.uid());

create policy "Users can update their profile"
  on public.profiles
  for update
  to authenticated
  using (id = auth.uid());

create policy "Messages are viewable by authenticated users"
  on public.messages
  for select
  to authenticated
  using (true);

create policy "Users can insert their own messages"
  on public.messages
  for insert
  to authenticated
  with check (user_id = auth.uid());
