create table if not exists public.book_store (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  genre text,
  published_year integer,
  created_at timestamptz not null default now()
);
